### ISSUE TITLE
minetest crashes because of the door api change

### ISSUE THREAD

**Issue by HybridDog** [DonBatman/mydoors#5]
https://github.com/minetest/minetest_game/commit/f600a9f645af40d22c8eb7c17aff89507b71816e

**Comment by JurajVajda** [comment]
:+1: 
renaming:
-       doors.register_door("my_castle_doors:door"..num, {
+       register_door("my_castle_doors:door"..num, {

in files:
	modified:   my_castle_doors/locked.lua
	modified:   my_castle_doors/unlocked.lua
	modified:   my_cottage_doors/locked.lua
	modified:   my_cottage_doors/unlocked.lua
	modified:   my_default_doors/locked.lua
	modified:   my_default_doors/unlocked.lua
	modified:   my_fancy_doors/locked.lua
	modified:   my_fancy_doors/unlocked.lua
	modified:   my_hidden_doors/init.lua
	modified:   my_misc_doors/locked.lua
	modified:   my_misc_doors/unlocked.lua
	modified:   my_old_doors/locked.lua
	modified:   my_old_doors/unlocked.lua

fixed the crash, but i don't think that's enough :/

**Comment by HybridDog** [comment]
The doors api changed without adding support to the old way of adding doors.

**Comment by JurajVajda** [comment]
that would be great :+1:

**Comment by DonBatman** [comment]
I will wait to see if they add support for the old way. If they do not within the next couple weeks then I will make a new repo with the new changes. That way people that have not updated will still be able to use this mod.

**Comment by HybridDog** [comment]
you could also do it in this repo and copy the current version into another branch

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest_game/issues/854
Someone else also has the problem.

**Comment by DonBatman** [comment]
I looked into the new door api. The problem is that the new doors are meshnodes instead of nodeboxes. I will have to redo all the textures and update the code to make it work with the new api. I am not able to put that much time into this right now. I will try to find time soon.

**Comment by DonBatman** [comment]
A temporary fix has been made. I added the the old doors mod code to the modpack. Renamed it to mdoors. Changed doors.register_door to mdoors.register_door.
I did a little testing and everything seems to work ok.
When I am able to I will change over to mesh doors.

**Comment by DonBatman** [comment]
updated to the new door api.
